var TRANSLATIONS_CS = {
  "hero_headline": "český pravák<br>surfuje do světa",
  "hero_subtext": "Jan Vítek 🍄‍🟫 na cestě na ISA World Surfing Games v El Salvadoru",
  "hero_cta": "→ mrkni na plán",

  "who_title": "kdo je jan vítek?",
  "who_heading": "<a href=\"https://humanscollective.com/\" target=\"_blank\" class=\"accent-link\">designer</a>, <a href=\"https://linktr.ee/janvitek\" target=\"_blank\" class=\"accent-link\">tvůrce</a>,<br>a reprezentant<br>mířící na ISA",
  "who_body": "Surfování jsem si do teď financoval sám. Pracuji na dálku. Nyní hledám partnera. Trénuji mezi Portugalskem, Francíí a Českem. Mířím na <a href=\"https://isasurf.org/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a>.",
  "who_tab_btn_kratce": "Krátce",
  "who_tab_btn_pribeh": "Příběh",
  "who_tab_kratce": "<p>Ve skutečnosti jsem levák, ale „svratecký pravák\", hřib – unikátní kousek z Vysočiny. Sem tam trénuji v Portugalsku s <a href=\"https://www.highintensitysurf.com/\" target=\"_blank\" class=\"accent-link\">HIST</a>. Pracuji jako brand designér a tvořím projekty. Procestoval jsem Nový Zéland, oceánii, Kalifornii a okolí Evropy.</p><p>Teď mířím na kvalifikaci na ISA World Surfing Games. Hledám partnera, který chce být součástí téhle cesty.</p>",
  "who_tab_pribeh": "<p>Pocházím ze Svratky na Vysočině – místa daleko od oceánu. S bráchou si říkáme „Svratečtí praváci\" — od tohoto potom slovo pravák (hřib, člověk na svém místě). Surfování pro mě vždycky znamenalo víc než jen sport. Byla to cesta, která mě naučila vytrvalosti, trpělivosti a odvaze jít za svým.</p><p>Díky surfingu jsem postupně procestoval různé části světa – od evropských pobřeží až po surfové destinace jako Nový Zéland nebo Hawaii. Surfování jsem si do teď financoval sám a kombinoval ho s prací na dálku jako brand designér a <a href=\"https://www.jdidohor.cz/home\" target=\"_blank\" class=\"accent-link\">podnikatel</a>.</p><p>Většinu času trénuji v Portugalsku s <a href=\"https://www.highintensitysurf.com/\" target=\"_blank\" class=\"accent-link\">HIST</a>. Závodím v česko-slovenském surfovém poháru a mým cílem je kvalifikace na ISA World Surfing Games v El Salvadoru.</p><p>Surfování je pro mě způsob, jak poznávat svět i sebe. Rád tím inspiruji ostatní – píle a trpělivost přináší výsledky.</p><p>Teď hledám partnera, který chce být součástí téhle cesty.</p>",
  "who_video_cta": "→ pusť si teaser",

  "why_title": "moje cesta",
  "why_text": "🏄 surfování je moje cesta poznání. posouvám své limity ✨, objevuji svět 🌍 a sdílím tuhle cestu s ostatními 🧘. protože věřím, že dobrodružství může inspirovat lidi plnit si své sny 🌊.",

  "results_title": "výsledky",
  "result_1": "🥈 2. místo Berber Cup 2026 Maroko CZ/SK",
  "result_2": "🥈 2. místo Berber Cup 2025 Maroko CZ/SK",
  "result_3": "🥉 3. místo v žebříčku CZ/SK Surf Cup 24–25",
  "result_4": "🌊 Semifinále Bali Big Wave 2024",
  "goals_label": "Pro co si jdu?",
  "goal_1": "🎯 <a href=\"https://www.surfchamp.cz/\" target=\"_blank\" class=\"accent-link\">Surfchamp 2026 Francie</a> – kvalifikace na ISA",
  "goal_2": "🌎 <a href=\"https://isasurf.org/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a>",
  "results_video_cta": "→ 2. místo Berber Cup 2026",

  "plan_title": "plán 2026",
  "plan_part1_title": "1. část – kvalifikace",
  "plan_1": "🏋️ duben – suchá příprava ČR (regenerace)",
  "plan_3": "📍 19. 5. – <a href=\"https://www.prazskejserf.cz/serfovej-open\" target=\"_blank\" class=\"accent-link\">PSK wavepool závod v Mnichově</a>",
  "plan_4": "🏄 květen/červen – tréning ve Francii",
  "plan_5": "🏆 20. 6. – <a href=\"https://www.surfchamp.cz/\" target=\"_blank\" class=\"accent-link\">Surfchamp surf závod ve Francii (ISA kvalifikace)</a>",
  "plan_part2_title": "2. část – příprava na ISA",
  "plan_6": "🏄‍ červenec/srpen – trénink Ericeira, Portugalsko",
  "plan_7": "🌎 září – <a href=\"https://isasurf.org/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a>",

  "sponsor_heading": "kolik dáš, tak velký logo budeš :)",
  "sponsor_pdf": "📄 stáhni si prezentaci (PDF)",
  "sponsor_body": "Doteď jsem to zvládl sám, ale rád bych se zaměřil na intenzivní přípravu s profíky, abych se kvalifikoval na světový závody.",
  "sponsor_cta": "→ pojďme spolupracovat 💪",

  "collab_text": "umím spolupracovat se značkama, jako třeba surfr, captain kombucha, jdi do hor, jsem model → <a href=\"https://www.elitelisbon.com/en/jan-vitek/\" target=\"_blank\" class=\"accent-link\">Elite Lisbon</a>",

  "partner_title": "co nabízím",
  "partner_cat1": "zážitky & obsah",
  "partner_talk": "🎤 přednáška/workshop ve firmě — osobní rozvoj, překonávání překážek, cesta za cílem",
  "partner_content": "📸 společný obsah — partnerská značka v reels/stories přímo z tréninků a závodů",
  "partner_bts": "🎥 behind-the-scenes série — autentický content z přípravy, který partner může sdílet",
  "partner_cat2": "pro zaměstnance partnera",
  "partner_surf": "🏄 surf experience — teambuilding s úvodem do surfingu (wavepool v Mnichově, týden u oceánu)",
  "partner_qa": "💪 motivační Q&A — online nebo naživo, ideální pro firemní eventy",
  "partner_cat3": "viditelnost",
  "partner_logo": "👕 logo na surfboardu a případně oblečení — viditelné v médiích a na závodech",
  "partner_social": "📱 zmínky na sociálních sítích — tagování partnera v postech z cest a závodů",
  "partner_web": "🌐 logo na webu — připravená sekce \"your logo here\"",

  "partner_cat4": "branding & design",
  "partner_brand_consult": "💡 brandingová konzultace — audit značky, brand strategie, vizuální identita",

  "stats_title": "reach & audience",
  "stats_subtitle": "proč spolupracovat",
  "stats_views": "organické zhlédnutí měsíčně",
  "stats_followers": "aktivní sledující",
  "stats_engagement": "míra zapojení",
  "stats_media": "zmínky v médiích",
  "stats_desc": "Moje publikum tvoří lidé, kteří mají blízko k přírodě, dobrodružství a vlastní tvorbě. Jsou to lidé, kteří chtějí žít aktivně, objevovat svět a hledat vlastní cestu – ať už skrze sport, cestování nebo projekty, které tvoří. Sdílím dobrodružství od oceánu, z hor a vlastních projektů, abych inspiroval k aktivnímu a svobodnému životu.",
  "stats_cta": "→ spolupracujme",

  "contact_title": "podpoř mě a pojďme inspirovat spolu 💪",
  "copy_feedback": "Zkopírováno!",

  "social_title": "sleduj moji cestu 👣",

  "bmaw_title": "spolupráce 1-on-1, která má smysl ☕",
  "bmaw_block1_title": "🧠 brand / business / brain",
  "bmaw_block1_body": "Řešíš značku, projekt nebo kam se posunout dál?<br>Potřebuješ si ujasnit směr, strategii nebo jen získat nový pohled? Můžeme to spolu projít.",
  "bmaw_block1_price_label": "1-on-1 konzultace ☕",
  "bmaw_block1_price1": "30 € / 30 min",
  "bmaw_block1_price2": "50 € / 60 min",
  "bmaw_block2_title": "🌊 surfing / sport",
  "bmaw_block2_body": "Chceš poradit se svým surfingem nebo se svojí sportovní / mentální přípravou?",
  "bmaw_block2_price_label": "sport / surf video coaching 🏄",
  "bmaw_block2_price": "20 € / call",
  "bmaw_block3_title": "🤝 rezervace",
  "bmaw_block3_body": "Rezervace probíhá přes hodinový slot — pokud chceš jen 30 min, napiš to do poznámky, stejně tak i téma, které budeme řešit.<br><br>Call si můžeš rezervovat bez závazku — pokud ti to bude dávat smysl, podpoříš mě po něm.",
  "bmaw_block3_support": "→ podpoříš tím moji přípravu na kvalifikaci 💪",
  "bmaw_cta": "→ bookni si termín ⏰",
  "bmaw_donate": "⭐ Baví tě to co dělám a chceš mě podpořit jen tak? Můžeš <a href=\"https://buymeacoffee.com/wonderwayofj\" target=\"_blank\" class=\"accent-link\">zde</a>. 🙂",

  "nav_contact": "→ kontakt",

  "partners_main": "hlavní partneři",
  "partners_official": "oficiální partneři",
  "partners_media": "mediální partneři"
};
