var TRANSLATIONS_CS = {
  "hero_badge": "‼️ kvalifikován na isa · peru 2026",
  "hero_headline": "český <span class='pravak-hover'>pravák<sup class='pravak-sup'>*</sup></span><br>surfuje do světa",
  "hero_subtext": "Jan Vítek 🍄‍🟫 reprezentuje Česko na ISA World Surfing Games v Peru · 6.–15. 11. 2026",
  "hero_cta": "→ mrkni na plán",

  "who_title": "kdo je jan vítek?",
  "who_heading": "reprezentant ČR<br>na ISA v Peru,<br><a href=\"https://humanscollective.com/\" target=\"_blank\" class=\"accent-link\">designer</a> a <a href=\"https://linktr.ee/janvitek\" target=\"_blank\" class=\"accent-link\">tvůrce</a>",
  "who_tab_btn_kratce": "Krátce",
  "who_tab_btn_pribeh": "Příběh",
  "who_tab_kratce": "<p>Jako kokosy na sněhu, tak já jsem český pravák * (hříbek) jedoucí na surfové mistrovství světa do Peru. Hledám partnery, kteří by chtěli být na této unikátní cestě.</p>",
  "who_tab_pribeh": "<p>Pocházím ze Svratky na Vysočině – místa daleko od oceánu. S bráchou si říkáme „* Svratečtí praváci\" — od tohoto potom slovo pravák (hřib, člověk na svém místě). Surfování pro mě vždycky znamenalo víc než jen sport. Byla to cesta, která mě naučila vytrvalosti, trpělivosti a odvaze jít za svým.</p><p>Díky surfingu jsem postupně procestoval různé části světa – od evropských pobřeží až po surfové destinace jako Nový Zéland nebo Hawaii. Surfování jsem si do teď financoval sám a kombinoval ho s prací na dálku jako brand designér a <a href=\"https://www.jdidohor.cz/home\" target=\"_blank\" class=\"accent-link\">podnikatel</a>.</p><p>Většinu času trénuji v Portugalsku s <a href=\"https://www.highintensitysurf.com/\" target=\"_blank\" class=\"accent-link\">HIST</a>. Závodím v česko-slovenském surfovém poháru a v roce 2026 jsem se kvalifikoval na ISA World Surfing Games v Peru. Cítím se trochu jako jamajský bobový tým na olympiádě — kokos na sněhu. Můj cíl: zjistit, jak daleko se dostanu proti nejlepším surfařům planety.</p><p>Surfování je pro mě způsob, jak poznávat svět i sebe. Rád tím inspiruji ostatní – píle a trpělivost přináší výsledky.</p><p>Teď hledám partnera, který chce být součástí téhle cesty.</p>",
  "who_video_cta": "→ pusť si teaser",

  "why_title": "moje cesta",
  "why_text": "🏄 surfování je moje cesta poznání. posouvám své limity ✨, objevuji svět 🌍 a sdílím tuhle cestu s ostatními 🧘. protože věřím, že dobrodružství může inspirovat lidi plnit si své sny 🌊. nyní mě čeká mistrovství světa v peru 🇵🇪 úlet.",

  "results_title": "výsledky",
  "result_1": "🥈 2. místo Berber Cup 2026 Maroko CZ/SK",
  "result_2": "🏄 7. místo Caparica 2025",
  "result_3": "🥈 2. místo Berber Cup 2025 Maroko CZ/SK",
  "result_4": "🥉 3. místo v žebříčku CZ/SK Surf Cup 24–25",
  "result_5": "🌊 Semifinále Bali Big Wave 2024",
  "goals_label": "Co mě čeká",
  "goal_1": "🌎 <a href=\"https://isasurf.org/peru-will-host-2026-isa-world-surfing-games-at-punta-rocas/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a> – Peru, 6.–15. 11. 2026",
  "goal_2": "💪 přijet do Peru připravený tak, aby jediným limitem byl můj surfing — ne fyzička, vybavení ani nervy",
  "results_video_cta": "→ 2. místo Berber Cup 2026",

  "team_title": "🇨🇿 český tým na ISA v Peru",
  "team_isa": "<a href=\"https://isasurf.org/peru-will-host-2026-isa-world-surfing-games-at-punta-rocas/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a> jsou mistrovství světa v surfingu. Pořádá je International Surfing Association — mezinárodní federace uznaná Mezinárodním olympijským výborem. Nejezdí se za klub ani sám za sebe, ale za zemi: každý stát vysílá národní tým a výsledky se sčítají i do týmového pořadí. V roce 2026 se závodí v peruánském Punta Rocas. Ročník 2026 je navíc jedním z prvních kvalifikačních kroků k olympijským hrám LA28: nejlepší týmy si tu vybojují místenku pro svou zemi.",
  "team_role": "reprezentant ČR",
  "team_role2": "reprezentant ČR",

  "plan_title": "plán 2026",
  "plan_part1_title": "✅ 1. část – kvalifikace (splněno)",
  "plan_1": "🥈 Berber Cup Maroko – 2. místo",
  "plan_3": "🏄 Caparica, Portugalsko – 7. místo",
  "plan_4": "🎟️ místo na mistrovství světa v Peru",
  "plan_part2_title": "2. část – příprava na Peru",
  "plan_6": "🏄 září – příprava Portugalsko",
  "plan_7": "🏆 1.–6. 10. – závod Caparica",
  "plan_8": "🏄 říjen/listopad – příprava Peru",
  "plan_9": "🌎 6.–15. 11. – <a href=\"https://isasurf.org/peru-will-host-2026-isa-world-surfing-games-at-punta-rocas/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a>, Peru",

  "sponsor_eyebrow": "hledám partnery",
  "sponsor_heading": "kolik dáš, tak velký logo budeš :)",
  "sponsor_logo_note": "logo pojede na mistrovství světa v Peru 🇵🇪",
  "sponsor_pdf": "📄 stáhni si prezentaci (PDF)",
  "sponsor_body": "Veškerou cestu jsem si dosud financoval sám. Budu rád, když se na ISA vydám s podporou partnera, kterému bude tahle cesta dávat smysl. Stáhni si můj pitch, nebo mi rovnou napiš e-mail.",
  "sponsor_cta": "→ pojďme spolupracovat 💪",

  "tier_main_name": "⭐ hlavní partner",
  "tier_main_price": "rozsah domluvíme individuálně",
  "tier_main_who": "1 partner",
  "tier_main_b1": "👕 dominantní logo na surfboardu a vybavení",
  "tier_main_b2": "🎥 pravidelný content z přípravy a z Peru",
  "tier_main_b3": "🌐 prezentace na webu a sociálních sítích",
  "tier_main_b4": "🎤 přednáška nebo workshop ve firmě",
  "tier_main_b5": "🏄 surf experience pro tebe i tým",
  "tier_partner_name": "🔥 partner",
  "tier_partner_price": "rozsah domluvíme individuálně",
  "tier_partner_who": "2–3 partneři",
  "tier_partner_b1": "👕 logo na vybavení nebo oblečení",
  "tier_partner_b2": "🎥 zmínky v obsahu ze závodů a tréninků",
  "tier_partner_b3": "🌐 logo na webu a v prezentaci",
  "tier_supporter_name": "🌱 podporovatel",
  "tier_supporter_price": "kolik uznáš za vhodné",
  "tier_supporter_who": "libovolně",
  "tier_supporter_b1": "🌐 logo na webu",
  "tier_supporter_b2": "📱 zmínka na sociálních sítích",
  "tier_supporter_b3": "🎥 možnost využití mého obsahu",

  "collab_text": "umím spolupracovat se značkama, jako třeba surfr, captain kombucha, jdi do hor, jsem model → <a href=\"https://www.elitelisbon.com/en/jan-vitek/\" target=\"_blank\" class=\"accent-link\">Elite Lisbon</a>",

  "partner_title": "co nabízím",
  "partner_cat1": "zážitky & obsah",
  "partner_talk": "🎤 přednáška/workshop ve firmě — osobní rozvoj, překonávání překážek, cesta za cílem",
  "partner_content": "📸 společný obsah — partnerská značka v reels/stories přímo z tréninků a závodů",
  "partner_bts": "🎥 behind-the-scenes série — autentický content z přípravy, který partner může sdílet",
  "partner_cat2": "pro zaměstnance partnera",
  "partner_surf": "🏄 surf experience — teambuilding s úvodem do surfingu (wavepool v Mnichově, týden u oceánu)",
  "partner_qa": "💪 motivační Q&A — online nebo naživo, ideální pro firemní eventy",
  "partner_cat3": "viditelnost",
  "partner_logo": "👕 logo na surfboardu a případně oblečení — viditelné v médiích a na závodech",
  "partner_social": "📱 zmínky na sociálních sítích — tagování partnera v postech z cest a závodů",
  "partner_web": "🌐 logo na webu — připravená sekce \"your logo here\"",

  "partner_cat4": "branding & design",
  "partner_brand_consult": "💡 brandingová konzultace — audit značky, brand strategie, vizuální identita",

  "stats_title": "reach & audience",
  "stats_subtitle": "proč spolupracovat",
  "stats_views": "organické zhlédnutí měsíčně",
  "stats_followers": "aktivní sledující",
  "stats_engagement": "míra zapojení",
  "stats_media": "zmínky v médiích",
  "stats_desc": "Moje publikum tvoří lidé, kteří mají blízko k přírodě, dobrodružství a vlastní tvorbě. Jsou to lidé, kteří chtějí žít aktivně, objevovat svět a hledat vlastní cestu – ať už skrze sport, cestování nebo projekty, které tvoří. Sdílím dobrodružství od oceánu, z hor a vlastních projektů, abych inspiroval k aktivnímu a svobodnému životu.",
  "stats_cta": "→ spolupracujme",

  "contact_title": "podpoř mě a pojďme inspirovat spolu 💪",
  "copy_feedback": "Zkopírováno!",

  "social_title": "sleduj moji cestu 👣",

  "bmaw_title": "spolupráce 1-on-1, která má smysl ☕",
  "bmaw_block1_title": "🧠 brand / business / brain",
  "bmaw_block1_body": "Řešíš značku, projekt nebo kam se posunout dál?<br>Potřebuješ si ujasnit směr, strategii nebo jen získat nový pohled? Můžeme to spolu projít.",
  "bmaw_block1_price_label": "1-on-1 konzultace ☕",
  "bmaw_block1_price1": "30 € / 30 min*",
  "bmaw_block1_price2": "50 € / 60 min*",
  "bmaw_block2_title": "🌊 surfing / sport",
  "bmaw_block2_body": "Chceš poradit se svým surfingem nebo se svojí sportovní / mentální přípravou?",
  "bmaw_block2_price_label": "sport / surf video coaching 🏄",
  "bmaw_block2_price": "20 € / call*",
  "bmaw_block3_title": "🤝 rezervace",
  "bmaw_block3_body": "Rezervace probíhá přes hodinový slot — pokud chceš jen 30 min, napiš to do poznámky, stejně tak i téma, které budeme řešit.<br><br>* 💸 Call si můžeš rezervovat bez závazku — pokud ti to bude dávat smysl, podpoříš mě po něm a cenu si nakonec určíš sám po callu, jak ti to bude vyhovovat.",
  "bmaw_block3_support": "→ podpoříš tím moji přípravu na mistrovství světa 💪",
  "bmaw_cta": "→ bookni si termín ⏰",
  "bmaw_donate": "Baví tě to co dělám a chceš mě podpořit jen tak? Můžeš <a href=\"https://buymeacoffee.com/wonderwayofj\" target=\"_blank\" class=\"accent-link\">zde</a>.",

  "nav_contact": "→ kontakt",

  "partners_main": "partneři",
  "partners_official": "oficiální partneři",
  "partners_media": "mediální partneři"
};
