var TRANSLATIONS_EN = {
  "hero_headline": "a czech goofy<br>surfing the world",
  "hero_subtext": "Jan Vítek on his way to the ISA World Surfing Games in El Salvador",
  "hero_cta": "→ check the plan",

  "who_title": "who is jan vítek?",
  "who_heading": "<a href=\"https://humanscollective.com/\" target=\"_blank\" class=\"accent-link\">designer</a>, <a href=\"https://linktr.ee/janvitek\" target=\"_blank\" class=\"accent-link\">entrepreneur</a>,<br>a competitor heading to ISA",
  "who_body": "I've been self-funding my surfing until now. I work remotely. Now I'm looking for a partner. I train between Portugal, France and Czechia. Heading to the <a href=\"https://isasurf.org/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a>.",
  "who_tab_btn_kratce": "In brief",
  "who_tab_btn_pribeh": "Story",
  "who_tab_kratce": "<p>I'm a surfer from Czechia. I train in Portugal with <a href=\"https://www.highintensitysurf.com/\" target=\"_blank\" class=\"accent-link\">HIST</a>. I work as a brand designer and build creative projects. I've travelled through New Zealand, Oceania, California and around Europe.</p><p>Now I'm heading for ISA World Surfing Games qualification. I'm looking for a partner who wants to be part of this journey.</p>",
  "who_tab_pribeh": "<p>I come from a small town called Svratka in the Vysočina region of the Czech Republic – a place far from the ocean. That's exactly why surfing always meant more to me than just a sport. It was a path that taught me persistence, patience and the courage to go after what I want.</p><p>Thanks to surfing I gradually travelled different parts of the world – from European coastlines to surf destinations like New Zealand or Hawaii. I've been self-funding my surfing all along, combining it with remote work as a brand designer and <a href=\"https://www.jdidohor.cz/home\" target=\"_blank\" class=\"accent-link\">entrepreneur</a>.</p><p>I spend most of my time training in Portugal with <a href=\"https://www.highintensitysurf.com/\" target=\"_blank\" class=\"accent-link\">HIST</a>. I compete in the Czech-Slovak Surf Cup and my goal is to qualify for the ISA World Surfing Games in El Salvador.</p><p>Surfing is my way of discovering the world and myself. I love inspiring others – persistence and patience bring results.</p><p>Now I'm looking for a partner who wants to be part of this journey.</p>",
  "who_video_cta": "→ watch the teaser",

  "why_title": "my journey",
  "why_text": "🏄 surfing is my path of discovery. i push my limits ✨, explore the world 🌍 and share this journey with others 🧘. because i believe adventure can inspire people to pursue their dreams 🌊.",

  "results_title": "results",
  "result_1": "🥈 2nd place Berber Cup 2026 Morocco CZ/SK",
  "result_2": "🥈 2nd place Berber Cup 2025 Morocco CZ/SK",
  "result_3": "🥉 3rd place in CZ/SK Surf Cup 24–25 rankings",
  "result_4": "🌊 Semifinal Bali Big Wave 2024",
  "goals_label": "What am I going for?",
  "goal_1": "🎯 <a href=\"https://www.surfchamp.cz/\" target=\"_blank\" class=\"accent-link\">Surfchamp 2026 France</a> – ISA qualifier",
  "goal_2": "🌎 <a href=\"https://isasurf.org/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a>",
  "results_video_cta": "→ 2nd place Berber Cup 2026",

  "plan_title": "plan 2026",
  "plan_part1_title": "part 1 – qualification",
  "plan_1": "🏋️ april – dry training in Czechia (recovery)",
  "plan_3": "📍 May 19 – <a href=\"https://www.prazskejserf.cz/serfovej-open\" target=\"_blank\" class=\"accent-link\">PSK wavepool contest in Munich</a>",
  "plan_4": "🏄 may/june – training in France",
  "plan_5": "🏆 June 20 – <a href=\"https://www.surfchamp.cz/\" target=\"_blank\" class=\"accent-link\">Surfchamp surf contest in France (ISA qualification)</a>",
  "plan_part2_title": "part 2 – ISA preparation",
  "plan_6": "🏄‍ july/august – training in Ericeira, Portugal",
  "plan_7": "🌎 september – <a href=\"https://isasurf.org/\" target=\"_blank\" class=\"accent-link\">ISA World Surfing Games</a>",

  "sponsor_heading": "the more you give, the bigger your logo gets :)",
  "sponsor_pdf": "📄 download the presentation (PDF)",
  "sponsor_body": "I've managed on my own until now, but I'd like to focus on intensive training with professionals to qualify for the world championships.",
  "sponsor_cta": "→ let's work together 💪",

  "collab_text": "I know how to collaborate with brands like surfr, captain kombucha, jdi do hor, I'm a model → <a href=\"https://www.elitelisbon.com/en/jan-vitek/\" target=\"_blank\" class=\"accent-link\">Elite Lisbon</a>",

  "partner_title": "things i offer",
  "partner_cat1": "experiences & content",
  "partner_talk": "🎤 talk/workshop at your company — personal growth, overcoming obstacles, chasing goals",
  "partner_content": "📸 co-created content — your brand in reels/stories straight from training and competitions",
  "partner_bts": "🎥 behind-the-scenes series — authentic prep content your brand can share",
  "partner_cat2": "for your team",
  "partner_surf": "🏄 surf experience — team building with an intro to surfing (Munich wavepool, a week by the ocean)",
  "partner_qa": "💪 motivational Q&A — online or in-person, ideal for corporate events",
  "partner_cat3": "visibility",
  "partner_logo": "👕 logo on surfboard and apparel — visible in media and at competitions",
  "partner_social": "📱 social media mentions — tagging your brand in posts from trips and competitions",
  "partner_web": "🌐 logo on the website — dedicated \"your logo here\" section",

  "partner_cat4": "branding & design",
  "partner_brand_consult": "💡 branding consultation — brand audit, brand strategy, visual identity",

  "stats_title": "reach & audience",
  "stats_subtitle": "why work together",
  "stats_views": "organic views monthly",
  "stats_followers": "active followers",
  "stats_engagement": "engagement rate",
  "stats_media": "media features",
  "stats_desc": "My audience are people who are close to nature, adventure and their own creative work. They want to live actively, explore the world and find their own path – whether through sport, travel or projects they create. I share adventures from the ocean, mountains and my own projects to inspire an active and free life.",
  "stats_cta": "→ let's work together",

  "contact_title": "support me and let's inspire together 💪",
  "copy_feedback": "Copied!",

  "social_title": "follow my journey 👣",

  "bmaw_title": "1-on-1 consultation that matters ☕",
  "bmaw_block1_title": "🧠 brand / business / brain",
  "bmaw_block1_body": "Working on a brand, project or wondering where to move next?<br>Need to clarify direction, strategy — or just get a fresh perspective? Let's talk it through.",
  "bmaw_block1_price_label": "1-on-1 consultation ☕",
  "bmaw_block1_price1": "€30 / 30 min",
  "bmaw_block1_price2": "€50 / 60 min",
  "bmaw_block2_title": "🌊 surfing / sport",
  "bmaw_block2_body": "Want advice on your surfing — or on your physical / mental prep?",
  "bmaw_block2_price_label": "sport / surf video coaching 🏄",
  "bmaw_block2_price": "€20 / call",
  "bmaw_block3_title": "🤝 booking",
  "bmaw_block3_body": "Booking goes through an hourly slot — if you only want 30 min, just add a note, along with the topic we'll cover.<br><br>You can book the call with no commitment — if it feels right, you can support me afterwards and set the price yourself, whatever works for you.",
  "bmaw_block3_support": "→ you'll support my qualification preparation 💪",
  "bmaw_cta": "→ book a slot ⏰",
  "bmaw_donate": "⭐ Do you enjoy what I do and want to support me just because? You can <a href=\"https://buymeacoffee.com/wonderwayofj\" target=\"_blank\" class=\"accent-link\">here</a>. 🙂",

  "nav_contact": "→ contact",

  "partners_main": "main partners",
  "partners_official": "official partners",
  "partners_media": "media partners"
};
